/*
 * Нетрика OTRS API
 * Интеграционный профиль системы регистрации запросов на обслуживание OTRS
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UpdateTicketTicket;
import java.io.IOException;

/**
 * UpdateTicket
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T07:29:17.387Z")
public class UpdateTicket {
  @SerializedName("Password")
  private String password = null;

  @SerializedName("UserLogin")
  private String userLogin = null;

  @SerializedName("TicketID")
  private String ticketID = null;

  @SerializedName("Ticket")
  private UpdateTicketTicket ticket = null;

  public UpdateTicket password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(example = "router1966", value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UpdateTicket userLogin(String userLogin) {
    this.userLogin = userLogin;
    return this;
  }

   /**
   * Get userLogin
   * @return userLogin
  **/
  @ApiModelProperty(example = "d.parkhimovich@netrika.ru", value = "")
  public String getUserLogin() {
    return userLogin;
  }

  public void setUserLogin(String userLogin) {
    this.userLogin = userLogin;
  }

  public UpdateTicket ticketID(String ticketID) {
    this.ticketID = ticketID;
    return this;
  }

   /**
   * Get ticketID
   * @return ticketID
  **/
  @ApiModelProperty(example = "1487", value = "")
  public String getTicketID() {
    return ticketID;
  }

  public void setTicketID(String ticketID) {
    this.ticketID = ticketID;
  }

  public UpdateTicket ticket(UpdateTicketTicket ticket) {
    this.ticket = ticket;
    return this;
  }

   /**
   * Get ticket
   * @return ticket
  **/
  @ApiModelProperty(value = "")
  public UpdateTicketTicket getTicket() {
    return ticket;
  }

  public void setTicket(UpdateTicketTicket ticket) {
    this.ticket = ticket;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateTicket updateTicket = (UpdateTicket) o;
    return Objects.equals(this.password, updateTicket.password) &&
        Objects.equals(this.userLogin, updateTicket.userLogin) &&
        Objects.equals(this.ticketID, updateTicket.ticketID) &&
        Objects.equals(this.ticket, updateTicket.ticket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, userLogin, ticketID, ticket);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTicket {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    userLogin: ").append(toIndentedString(userLogin)).append("\n");
    sb.append("    ticketID: ").append(toIndentedString(ticketID)).append("\n");
    sb.append("    ticket: ").append(toIndentedString(ticket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

