/*
 * Нетрика OTRS API
 * Интеграционный профиль системы регистрации запросов на обслуживание OTRS
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.UpdateTicket;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for _Api
 */
@Ignore
public class _ApiTest {

    private final _Api api = new _Api();

    
    /**
     * Принимает номер тикета
     *
     * Возвращает JSON объект из 38 полей с информацией о заявке
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ticketGetTest() throws ApiException {
        String ticketID = null;
        String userLogin = null;
        String password = null;
        api.ticketGet(ticketID, userLogin, password);

        // TODO: test validations
    }
    
    /**
     * Принимает номер тикета и очередь
     *
     * Возвращает JSON объект с массивом тикетов
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ticketSearchTest() throws ApiException {
        String userLogin = null;
        String password = null;
        String queues = null;
        String ticketNumber = null;
        api.ticketSearch(userLogin, password, queues, ticketNumber);

        // TODO: test validations
    }
    
    /**
     * Принимает номер тикета и параметры
     *
     * Возвращает JSON объект из 2 полей с номером тикета при успехе
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ticketUpdateTest() throws ApiException {
        UpdateTicket json = null;
        api.ticketUpdate(json);

        // TODO: test validations
    }
    
}
